# -*- coding: utf-8 -*-
"""rest_rev_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Poh4lB8qUVK7MHXjBdRCSiwHmi_n46c
"""

import streamlit as st
import pandas as pd
from transformers import pipeline

# Page setup
st.set_page_config(page_title="Restaurant Review Analyzer", layout="wide")

st.title("🍽️ Restaurant Review Analyzer")
st.write("Analyze restaurant feedback using Hugging Face NLP models.")

# Model Caching for smooth performance
@st.cache_resource
def load_sentiment_model(model_name):
    return pipeline("text-classification", model=model_name, use_fast=False)

@st.cache_resource
def load_zeroshot_model():
    return pipeline("zero-shot-classification", model="MoritzLaurer/mDeBERTa-v3-base-mnli-xnli")

# Sidebar - Settings
st.sidebar.header("Model Settings")
sentiment_model_choice = st.sidebar.selectbox(
    "Choose Sentiment Model:",
    [
        "cardiffnlp/twitter-roberta-base-sentiment-latest",
        "cardiffnlp/twitter-xlm-roberta-base-sentiment",
        "lxyuan/distilbert-base-multilingual-cased-sentiments-student"
    ]
)

# User Input Section
st.header("1. Input Review Text")
user_input = st.text_area(
    "Enter a restaurant review:",
    "The food was delicious and fresh, but we had to wait 45 minutes to get seated."
)

candidate_topics = [
    "Food Quality", "Service", "Price",
    "Cleanliness", "Atmosphere", "Location", "Waiting Time"
]

if st.button("Analyze Review"):
    if user_input.strip() != "":
        # Load pipelines
        sentiment_pipe = load_sentiment_model(sentiment_model_choice)
        zeroshot_pipe = load_zeroshot_model()

        # Inference
        sent_res = sentiment_pipe(user_input)[0]
        topic_res = zeroshot_pipe(user_input, candidate_labels=candidate_topics)

        # Display Results
        col1, col2 = st.columns(2)

        with col1:
            st.subheader("Task A: Sentiment Result")
            st.metric("Predicted Sentiment", sent_res['label'].capitalize())
            st.metric("Confidence Score", f"{sent_res['score']:.4f}")
            st.json({
                "label": sent_res['label'],
                "score": float(sent_res['score']),
                "metadata": "huggingface_AI_model"
            })

        with col2:
            st.subheader("Task B: Topic Classification")
            top_topic = topic_res['labels'][0]
            top_score = topic_res['scores'][0]
            st.metric("Main Topic", top_topic)
            st.metric("Topic Confidence Score", f"{top_score:.4f}")

            # Display full topic probability table
            topic_df = pd.DataFrame({
                "Topic": topic_res['labels'],
                "Confidence": topic_res['scores']
            })
            st.dataframe(topic_df)
    else:
        st.warning("Please enter a review first.")

